CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260126130546_InitialPostgreSQL') THEN
    CREATE TABLE public."Courses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text,
        "Price" numeric(18,2) NOT NULL,
        "Deleted" boolean NOT NULL,
        CONSTRAINT "PK_Courses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260126130546_InitialPostgreSQL') THEN
    CREATE TABLE public."Lessons" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Subject" text,
        "CourseId" integer NOT NULL,
        "Deleted" boolean NOT NULL,
        CONSTRAINT "PK_Lessons" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Lessons_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260126130546_InitialPostgreSQL') THEN
    CREATE INDEX "IX_Courses_Name" ON public."Courses" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260126130546_InitialPostgreSQL') THEN
    CREATE INDEX "IX_Lessons_CourseId" ON public."Lessons" ("CourseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260126130546_InitialPostgreSQL') THEN
    CREATE INDEX "IX_Lessons_Subject" ON public."Lessons" ("Subject");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260126130546_InitialPostgreSQL') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260126130546_InitialPostgreSQL', '10.0.0');
    END IF;
END $EF$;
COMMIT;

