apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-cms-config
  labels:
    app: landing-cms
data:
  # URL для CDN медиафайлов (оставить пустым для локального хранения)
  media-cdn: ""
  
  # Настройки логирования
  logging-level: "Information"
  
  # Настройки приложения
  aspnetcore-environment: "Production"
